### ISSUE TITLE
Is numpy optional?

### ISSUE THREAD

**Issue by ZeroChaos-** [xmikos/simplespectral#1]
The readme suggests numpy is required, but when discussing usage the fft uses numpy only as a last resort.  Is numpy used if scipy or pyfft are installed?

**Comment by xmikos** [comment]
NumPy is required dependency. Even if I don't use numpy.fft functions (only as fallback), numpy is used for basic arrays (without it Python would be very slow). SciPy also uses NumPy internally and so does pyFFTW.
